# version: "3.9"

services:
  influxdb:
    container_name: demo-influx
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUX_HOST=http://influxdb
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - .docker/influxdb/influxdb-data:/var/lib/influxdb
      - .docker/influxdb/influxdb2-data:/var/lib/influxdb2
      - .docker/influxdb/etc:/etc/influxdb2
    networks:
      mynetwork:

  grafana:
    container_name: demo-grafana
    image: grafana/grafana:8.2.6
    ports:
      - "3001:3001"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - .docker/grafana/grafana-data:/var/lib/grafana
      - ./Grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      mynetwork:

networks:
  mynetwork:
    driver: bridge
