{
 "title": "SmartBan_v2",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "500ms",
 "templating": {
  "list": [
   {
    "name": "NodeId",
    "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: \"node-data\",\r\n  tag: \"NodeId\"\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ENV\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"Temperature\")\r\n  |> last()\r\n\r\nTempSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Temp\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nTempSeries |> yield()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ENV\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"Humidity\")\r\n  |> last()\r\n\r\nHumSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Hum\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nHumSeries |> yield()"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "RawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"GNSS\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n  |> drop(columns:[\"_start\",\"_stop\", \"_time\", \"_measurement\", \"SensorType\"])\r\n\r\nRawSeries |> yield()"
    }
   ]
  },
  {
   "title": "ECG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\"\r\n  )\r\n\r\nEcgSeries = RawSeries\r\n  |> filter(fn:(r) => r._field == \"ecg\")\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"ecg\"}))\r\n  |> keep(columns:FinalOutput)\r\n  |> yield(name:\"ecg\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Heart Rate Transition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "BPM" } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\", \"_time\"]\r\n\r\nfrom(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\" and \r\n    r._field == \"HR\")\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"HR\"}))\r\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ENV\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"Pressure\")\r\n  |> last()\r\n\r\nPressSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"Press\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nPressSeries |> yield()"
    }
   ]
  },
  {
   "title": "Imu_gyro",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"gyro_x\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"GX\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()\r\n"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"gyro_y\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"GY\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"gyro_z\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"GZ\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()\r\n"
    }
   ]
  },
  {
   "title": "PPG",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"PPG\" and\r\n    r.NodeId == \"${NodeId}\"\r\n  )\r\n\r\nPpgSeries = RawSeries\r\n  |> filter(fn:(r) => r._field == \"ppg\")\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"ppg\"}))\r\n  |> keep(columns:FinalOutput)\r\n  |> yield(name:\"ppg\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "RRI Transition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\", \"_time\"]\r\n\r\nfrom(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\" and \r\n    r._field == \"RRI\")\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"RRI\"}))\r\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Heart Rate(by ECG)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "BPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\"]\r\n\r\nfrom(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\" and \r\n    r._field == \"HR\")\r\n  |> last()\r\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "ストレス指標(LF/HF)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_value\"]\r\n\r\nfrom(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\" and \r\n    r._field == \"LFHF\")\r\n  |> last()\r\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Imu_acc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"acc_x\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"AX\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()\r\n"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"acc_y\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"AY\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\",\"_value\"]\r\n\r\nRawSeries = from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"IMU\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r._field == \"acc_z\"\r\n  )\r\n\r\nNamedSeries = RawSeries\r\n  |> map(fn: (r) => ({_value:r._value, _time: r._time, _field: \"AZ\"}))\r\n  |> keep(columns:FinalOutput)\r\n\r\nNamedSeries |> yield()\r\n"
    }
   ]
  },
  {
   "title": "RRI_PSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"node-data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"ECG\" and\r\n    r.NodeId == \"${NodeId}\" and\r\n    r.dataType == \"RRI_PSD\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"SensorType\", \"NodeId\", \"dataType\"])\r\n  |> yield(name: \"RRI_PowerSectrum\")"
    }
   ]
  }
 ]
}